### ISSUE TITLE
Can't provide any args to list (sync)

### ISSUE THREAD

**Issue by ion-elgreco** [kr8s-org/kr8s#553]
### Which project are you reporting a bug for?

kr8s

### What happened?

The sync version of list doesn't allow any args to be passed, so you can't actually use it

**Comment by jacobtomlinson** [comment]
Yep I can reproduce. Having a concrete reproducible example makes debugging these things much faster.

E.g If you want to list Pods and filter by a label selector it is pot possible. The following reproducer works in `0.19.1` but not in `0.20.0`.

```python
>>> import kr8s
>>> pods = kr8s.objects.Pod.list(label_selector={'foo': 'bar'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: APIObjectSyncMixin.list() got an unexpected keyword argument 'label_selector'
```
